### ISSUE TITLE
Organizar dados coletados pelo sensor em estrutura de dados a ser definida.

### ISSUE THREAD

**Issue by marcelo-bn** [motechnology/Projeto-Integrador-II#10]

**Comment by marcelo-bn** [comment]
Objetivos: Organizar dados coletados pelo sensor DHT11 e transmitidos para o arduino, em uma estrutura de dados ainda não definida pela equipe.

**Comment by osvaldosneto** [comment]
A estrutura  para o armazenamento dos dados coletados nesta etapa do projeto ficou definida da como uma String contendo os seguintes campos:

 "periodo: (manhã/tarde/noite) temperatura: (valor) umidade: (valor)"

O código referente a esta parte do projeto está publicado em: https://github.com/motechnology/Projeto-Integrador-II/blob/master/sensor_DHT.ino

**Comment by marcelo-bn** [comment]
Sugestão de formato: [JSON](https://json.org).

**Comment by marcelo-bn** [comment]
A ver: https://arduinojson.org
