### ISSUE TITLE
Testar e desenvolver algoritmos do módulos Wi-Fi

### ISSUE THREAD

**Issue by marcelo-bn** [motechnology/Projeto-Integrador-II#11]

**Comment by marcelo-bn** [comment]
Objetivo: Realizar pequenos teste de envio de dados entre os módulos NRF24L01.

**Comment by osvaldosneto** [comment]
será documentado como ocorrerá a comunicação entre os módulos NRF24L01, ou seja, a direção da transmissão dos dados indicando o sentido da mensagem, assim como será demonstrado o código referente a esta tarefa.

**Comment by marcelo-bn** [comment]
O documento referente a esta parte do projeto está publicado em: https://motechnology.github.io/Documentos/post9.html
Nessa página está um link para os códigos desenvolvidos para esta etapa.
