### ISSUE TITLE
Estabilizar comunicação entre os rádios

### ISSUE THREAD

**Issue by marcelo-bn** [motechnology/Projeto-Integrador-II#12]

**Comment by marcelo-bn** [comment]
Objetivo: Certificar que os módulos NRF24L01 estão transmitindo e recebendo dados (dados de teste) de forma correta.

**Comment by osvaldosneto** [comment]
Será testado comunicação entre modulo receptor e transmissor, onde enviaremos um dado teste qualquer, iremos demonstrar através de imagens que a transmissão ocorreu conforme esperado, especificando a quantidade de erros que ocorreram na comunicação.

**Comment by marcelo-bn** [comment]
O documento referente a esta parte do projeto está publicado em:
https://motechnology.github.io/Documentos/post10.html

**Comment by marcelo-bn** [comment]
Depende do código de #11.
