### ISSUE TITLE
Estudar o json para formato dos dados coletados pelo arduino

### ISSUE THREAD

**Issue by marcelo-bn** [motechnology/Projeto-Integrador-II#13]

**Comment by marcelo-bn** [comment]
Objetivo: Realizar uma pesquisa a respeito do modelo de formatação de texto JSON para futuramente ser implementado no sistema em desenvolvimento.

**Comment by marcelo-bn** [comment]
O documento referente a esta parte do projeto está publicado em:
https://motechnology.github.io/Documentos/post8.html

**Comment by ghost** [comment]
No JSON os elementos do objeto são separados por vírgula.

**Comment by marcelo-bn** [comment]
Alteração realizada, obrigado pela sugestão :)

**Comment by marcelo-bn** [comment]
Sugestão: com o tamanho reduzido de mensagem entre os módulos coletor e transmissor, enviar em CSV entre os Arduinos, e somente JSON pleno na requisição POST com o servidor.
