### ISSUE TITLE
Densenvolver API do back-end

### ISSUE THREAD

**Issue by jenefferf** [motechnology/Projeto-Integrador-II#16]
Objetivo: definição da lista de URIs, tipos de operação (get, post, delete), formato de entradas e saídas.

**Comment by marcelo-bn** [comment]
O documento referente a esta parte do projeto está publicado em:
https://motechnology.github.io/Documentos/post13.html

**Comment by ghost** [comment]
A resposta `201 Created`, pelo que entendi da [documentação da Mozilla](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/201), se refere a criação de recursos do tipo URI. Assim, nas requisições `GET` não vejo como sendo uma resposta possível. Já nas requisições `POST` vejo apenas se for criado uma nova URI para consulta de medições com `GET`. Dessa forma, é preciso especificar o formato de resposta com a nova URI criada.

**Comment by ghost** [comment]
É possível usar uma mesma URI com métodos diferentes, no caso `GET` e `POST`. Porém, não é mais interessante deixar uma com autenticação (`POST`) e outra sem (`GET`), e por isso segmentar melhor os _endpoints_?

**Comment by marcelo-bn** [comment]
Alterações realizadas.
O documento referente a esta parte do projeto está publicado em:
https://motechnology.github.io/Documentos/post13.html
