### ISSUE TITLE
Definir estrutura dos dados armazenados no banco

### ISSUE THREAD

**Issue by jenefferf** [motechnology/Projeto-Integrador-II#17]

**Comment by jenefferf** [comment]
Objetivo: criação das coleções  de duas coleções. Um delas  irá armazenar o id e senha dos arduinos que compõem o  sistema  de coleta. A outra irá armazenar os dados das coletas.

**Comment by jenefferf** [comment]
Documento onde estou descrevendo como nosso banco está estruturado: https://docs.google.com/document/d/1cRnHWeleC0gmCIqm98Qa1oiZ8UYoCoSmlSvWZtTxaSk/edit?usp=sharing

**Comment by ghost** [comment]
Definir os atributos do JSON em cada coleção: obrigatórios, opcionais, formato etc.

**Comment by marcelo-bn** [comment]
O documento referente a esta parte do projeto foi publicado em:
https://motechnology.github.io/Documentos/post14.html
