### ISSUE TITLE
Conectividade IP no módulo de transmissão

### ISSUE THREAD

**Issue by jenefferf** [motechnology/Projeto-Integrador-II#18]
Implementar e validar a interface IEEE 802.11 do módulo de transmissão.

**Comment by marcelo-bn** [comment]
Objetivo: Realizar um teste de conexão do módulo NODEMCU.

**Comment by marcelo-bn** [comment]
O documento referente à esta parte do projeto está publicado em:
https://motechnology.github.io/Documentos/post15.html

**Comment by marcelo-bn** [comment]
O código desenvolvido está publicado em:
https://github.com/motechnology/Base-transmissora/blob/dev/tstemcu.ino
