### ISSUE TITLE
Adquirir sensores, componentes e microcontroladores

### ISSUE THREAD

**Issue by marcelo-bn** [motechnology/Projeto-Integrador-II#2]

**Comment by osvaldosneto** [comment]
Lista de componentes a adquirir:
_sensor de temperatura e umidade DHT11 (a adquirir)

Lista de componentes já adquiridos:
_arduino mega (propriedade da equipe)
_arduino uno (propriedade da equipe)
_2 módulos Wifi NRFL24L01 (cedido pelo IFSC)
_1 módulo Wifi ESP8266 (propriedade da equipe)
_2 fontes de alimentação (cedido pelo IFSC)
_2 protoboard (propriedade da equipe)
_kit jumper (propriedade da equipe)

**Comment by osvaldosneto** [comment]
todos os itens já foram adquiridos.
