### ISSUE TITLE
Documentação da api

### ISSUE THREAD

**Issue by jenefferf** [motechnology/Projeto-Integrador-II#22]

**Comment by jenefferf** [comment]
Documentação do código da API REST

**Comment by jenefferf** [comment]
A documentação do código está disponível do link: https://documenter.getpostman.com/view/8777140/SW18xFVT?version=latest

**Comment by ghost** [comment]
Informar também os códigos de resposta positiva: `200`, `201` etc.

**Comment by jenefferf** [comment]
Ok. Já adicionei ao documento.
