### ISSUE TITLE
Estudar e definir modo de transmissão e alimentação do sistema

### ISSUE THREAD

**Issue by jenefferf** [motechnology/Projeto-Integrador-II#5]

**Comment by marcelo-bn** [comment]
Objetivo: Documentar a tensão e corrente de operação dos componentes a serem usados nos módulos de transmissão e recepção da rede.  Também será declarado as frequências de operação que os módulos rádio/wifi irão operar.

**Comment by marcelo-bn** [comment]
O documento referente a esta parte do projeto está publicado na página: https://motechnology.github.io/Documentos/post2.html
