### ISSUE TITLE
Montar protótipo não funcional do módulo de transmissão.

### ISSUE THREAD

**Issue by marcelo-bn** [motechnology/Projeto-Integrador-II#7]

**Comment by marcelo-bn** [comment]
Objetivo: Realizar a montagem não funcional do módulo de transmissão para um melhor entendimento do projeto.

**Comment by osvaldosneto** [comment]
pinagens:
pino 1 : gnd arduino
pino 2 : vcc 3,3v arduino
pino 3 (chip enable) : pino 10 arduino
pino 4 (chip select not) : pino 9 arduino
pino 5 (serial clock) : pino 11 arduino
pino 6 (master out slave in) : pino 13 arduino
pino 7 (master in slave out) : pino 12 arduino
pino 8 (interrupt) : 

https://create.arduino.cc/projecthub/muhammad-aqib/nrf24l01-interfacing-with-arduino-wireless-communication-0c13d4

**Comment by marcelo-bn** [comment]
O documento referente a esta parte do projeto está publicado na página: https://motechnology.github.io/Documentos/post6.html
