### ISSUE TITLE
Desenvolver código em arduino para o sensor DHT11.

### ISSUE THREAD

**Issue by marcelo-bn** [motechnology/Projeto-Integrador-II#9]

**Comment by marcelo-bn** [comment]
Objetivo: Desenvolver código em arduino utilizando biblioteca (ainda não escolhida) referente ao sensor DHT11 para a coleta de dados (temperatura e umidade).

**Comment by osvaldosneto** [comment]
O código referente a esta parte do projeto está publicado em: https://github.com/motechnology/Projeto-Integrador-II/blob/master/sensor_DHT.ino

**Comment by marcelo-bn** [comment]
A biblioteca do sensor DHT11 para Arduino se encontra no seguinte endereço: https://github.com/motechnology/Projeto-Integrador-II/blob/master/DHTlib.zip

**Comment by marcelo-bn** [comment]
Sugestão: usar [submódulo do Git](https://git-scm.com/book/pt-br/v1/Ferramentas-do-Git-Submódulos).
